version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directories: ["/*"]          # every app folder
    schedule:
      interval: monthly
