#!/usr/bin/env bash
# ELOG app entrypoint: renders elogd.cfg from app options and starts elogd.
set -euo pipefail

OPTIONS=/data/options.json
CFG_DIR=/config                    # = /addon_configs/<slug>/ on the host
CFG="${CFG_DIR}/elogd.cfg"
DATA=/data/elog
LOGBOOK_DIR="${DATA}/logbooks"
PASSWD="${DATA}/passwd.xml"
RESOURCE_DIR=/opt/elog
PORT=8080

log() { echo "[$(date '+%F %T')] [elog] $*"; }

# Allow plain `docker run` testing outside Home Assistant
if [ ! -f "${OPTIONS}" ]; then
  log "No ${OPTIONS} found, using defaults (standalone mode)"
  mkdir -p /data
  cat > "${OPTIONS}" <<'JSON'
{"logbooks":[{"name":"General","description":"General purpose logbook"}],
 "authentication":false,"admin_user":"admin","self_register":1,"manage_config":true}
JSON
fi

opt() { jq -r "$1 | if . == null then \"\" else tostring end" "${OPTIONS}"; }

mkdir -p "${CFG_DIR}" "${LOGBOOK_DIR}"

render_config() {
  local auth admin selfreg url count name desc
  auth="$(opt '.authentication')"
  admin="$(opt '.admin_user')"
  selfreg="$(opt '.self_register')"
  url="$(opt '.url')"
  count="$(jq '.logbooks | length' "${OPTIONS}")"

  if [ "${count}" -eq 0 ]; then
    log "ERROR: at least one logbook must be configured"; exit 1
  fi

  {
    echo "# Generated by the ELOG Home Assistant app on $(date '+%F %T')."
    echo "# Set 'manage_config: false' in the app options to edit this file by hand."
    echo
    echo "[global]"
    echo "Port = ${PORT}"
    echo "Resource dir = ${RESOURCE_DIR}"
    echo "Logbook dir = ${LOGBOOK_DIR}"
    echo "Usr = elog"
    echo "Grp = elog"
    echo "Logbook tabs = 1"
    echo "Show top groups = 0"
    if [ -n "${url}" ]; then echo "URL = ${url}"; fi
    if [ "${auth}" = "true" ]; then
      echo "Password file = ${PASSWD}"
      if [ -n "${admin}" ]; then echo "Admin user = ${admin}"; fi
      echo "Self register = ${selfreg}"
      echo "Login expiration = 744"
    fi
    echo

    for ((i = 0; i < count; i++)); do
      name="$(opt ".logbooks[${i}].name")"
      desc="$(opt ".logbooks[${i}].description" | tr '\n' ' ' | sed 's/[[:space:]]*$//')"
      if [ "${name,,}" = "global" ]; then
        log "WARNING: skipping reserved logbook name '${name}'"; continue
      fi
      echo "[${name}]"
      if [ -n "${desc}" ]; then echo "Comment = ${desc}"; fi
      echo "Theme = default"
      echo "Attributes = Author, Type, Category, Subject"
      echo "Options Type = Routine, Problem, Fix, Info, Other"
      echo "Options Category = General, Hardware, Software, Network, Other"
      echo "Extendable Options = Category"
      echo "Required Attributes = Author, Subject"
      if [ "${auth}" = "true" ]; then
        echo "Preset Author = \$long_name"
        echo "Locked Attributes = Author"
      fi
      echo "Page Title = ELOG - \$subject"
      echo "Reverse sort = 1"
      echo "Quick filter = Date, Type, Category"
      echo
      mkdir -p "${LOGBOOK_DIR}/${name}"
    done
  } > "${CFG}.tmp"
  mv "${CFG}.tmp" "${CFG}"
}

if [ "$(opt '.manage_config')" = "true" ] || [ ! -f "${CFG}" ]; then
  log "Rendering ${CFG} from app options"
  render_config
else
  log "manage_config is off, using existing ${CFG} as-is"
fi

# elogd drops to user 'elog' after binding; it must own its data and config
chown -R elog:elog "${DATA}" "${CFG}"

log "Logbooks: $(jq -r '[.logbooks[].name] | join(", ")' "${OPTIONS}")"

# Extra ingress rewrite for the configured external URL (if any)
EXTRA=/run/elog-ingress-extra.conf
: > "${EXTRA}"
EXT_URL="$(opt '.url')"
if [ -n "${EXT_URL}" ]; then
  EXT_URL="${EXT_URL%/}/"
  echo "sub_filter '${EXT_URL}' '\$http_x_ingress_path/';" >> "${EXTRA}"
fi

log "Starting elogd on port ${PORT}"
"${RESOURCE_DIR}/bin/elogd" -c "${CFG}" -p "${PORT}" &
ELOG_PID=$!

log "Starting ingress proxy on port 8099"
nginx -g 'daemon off;' &
NGINX_PID=$!

shutdown() {
  log "Stopping"
  kill -TERM "${ELOG_PID}" "${NGINX_PID}" 2>/dev/null || true
  wait || true
  exit 0
}
trap shutdown TERM INT

# If either process dies, stop the other so the Supervisor sees the failure
code=0
wait -n "${ELOG_PID}" "${NGINX_PID}" || code=$?
log "A service exited (code ${code}), shutting down"
kill -TERM "${ELOG_PID}" "${NGINX_PID}" 2>/dev/null || true
wait || true
exit $(( code == 0 ? 1 : code ))
